name: build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare
      run: |
        sudo apt update
        sudo apt install -y ninja-build
        git clone https://github.com/emscripten-core/emsdk.git
        ./emsdk install latest
        ./emsdk activate latest
    - name: make
      run: ./build.sh
    - name: Archive dists
      uses: actions/upload-artifact@v4
      with:
        name: clangd
        path: pkg/dist
