name: build 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  builds:
      strategy:
        matrix:
          build_package: [clangd, clang]
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: prepare
        run: |
          sudo apt update
          sudo apt install -y ninja-build
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 250M
          key: ${{ runner.os }}-${{ matrix.build_package }}
      - name: make
        run: |
          source ./emsdk/emsdk_env.sh
          ./build.sh ${{ matrix.build_package }}
      - name: Archive dists
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build_package }}
          path: pkg/dist
  publish:
    needs: builds
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Download dists
      uses: actions/download-artifact@v4
      with:
        path: pkg/dist
    - uses: JS-DevTools/npm-publish@v3.1.1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        registry: "https://npm.pkg.github.com/"
        package: pkg
