name: build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: prepare
      run: |
        sudo apt update
        sudo apt install -y ninja-build
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
    - name: make
      run: |
        source ./emsdk/emsdk_env.sh
        ./build.sh
    - name: Archive dists
      uses: actions/upload-artifact@v4
      with:
        name: clang
        path: pkg/dist
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/
    - name: Download dists
      uses: actions/download-artifact@v4
      with:
        name: clang
        path: pkg/dist
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
